const vitalActionTypes = {
  GET_VITALS_START: "GET_VITALS_START",
  GET_VITALS_SUCCESS: "GET_VITALS_SUCCESS",
  GETGET_VITALS_FAILURE: "GET_VITALS_FAILURE",
  SET_VITALS: "SET_VITALS",
};

export default vitalActionTypes;
