const userActionTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

export default userActionTypes;
